<main>
    <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <h2>your order</h2>
                        <span>Details to details is what makes Hexashop different from the other themes.</span>
                    </div>
                    <form id="contact-form" data-mode='ajout' class="is-hidden ">
                                <table class="table border">
                                    <thead>
                                        <tr>
                                        <th scope="col">product</th>
                                        <th scope="col">quantity</th>
                                        <th scope="col">total</th>
                                        </tr>
                                    </thead>
                                    <tbody id="order">
                                    <?php foreach($affichOrder as $order) : ?>
                                        <tr>
                                        <td><?= $order['nom'] ?></td> 
                                        <td><?= $order['quantity'] ?></td>
                                        <td><?= $order['price'] * $order['quantity'] ?></td>
                                        
                                        <tr>
                                    
                                        <?php endforeach ;?>
                                        <tr>
                                            <td> <strong>TOTAL</strong></td>
                                            <td></td>
                                        <td><strong> <?= $order['total'] ?></strong>
                                            </td>
                                        </tr>


                                    </tbody>
                                </table>
                    </form>
                    <a href="shop.php" class="btn border" id="continue">continue</a>
                    <a href="#" class="btn  border" id="checkout">checkout</a>
                </div>
            </div>
    </div>
    <script src="../js/jquery/jquery-2.2.4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="panier.js"></script>
    <script src="checkout.js"></script>


</main>