
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <!-- <div class="divimghead"><img src="../photos/leaf-footer.png" alt=""></div> -->
        <div class="nav1">
            <p ><strong><a href="#" class="p-title" ><span class="title">Shop</span> Plants</a></strong></p>
            <ul class="linksoc">
                <li>
                    <a href="#"><i class="bi bi-facebook"></i></a>
                    <a href="#"><i class="bi bi-twitter"></i></a>
                    <a href="#"><i class="bi bi-instagram"></i></a>
                </li>
            </ul>
        </div>
        <ul class="nav justify-content-center bg-light menu-nav" id=" menu-nav">
        <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->

            <li class="nav-item">
                <a class="nav-link font-weight-bold active" href="index.php">home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" href="shop.php">shop</a>
            </li>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" href="register.php">register</a>
            </li>
            <?php if((isset($_SESSION['user_id'])) && (!empty($_SESSION['user_id']))):?>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" href="deconnected.php">deconnect</a>
            </li>
            <?php else :?>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" href="login.php">login</a>
            </li>
            <?php endif;?>
            <?php if((isset($_SESSION['user_id'])) && (!empty($_SESSION['user_id']))):?>
                <li class="scroll-to-section"><a href="panier.phtml"><i class="bi bi-cart-fill"></i></a></li>
            <?php endif;?>


        </ul>


        <div class="mobil-nav">
            <div class="menu-position">
                <div class="menu-header">
                    <input type="checkbox" class="chek">
                    <div class="menu-chek">
                        <div></div>
                    </div>
                    <div class=" menu">
                    <div>
                    <div>
                    </div>
                    </div>
                    </div> 
                </div>
            </div>
        </div>


        <?php include $template; ?>
    </header>
    <footer >
        <div class="delivery">
            <img src="../photos/delivery-van-christmas.svg" alt="dilevry">
            <p>Free standard delivery on orders over £50</p>
        </div>
        <div class="footer">
            <div class="service">
                <h3>HELP</h3>
                <p>Need to get in touch?</p>

                <p>Just use the help widget to send a message to the team.</p>

            <p> Customer service opening hours:</p>

            <span> Monday to Sunday 9am-10pm <span>

            <p> Live chat is available 10am-5pm Monday to Sunday</p>
            </div>
            <div>
                <h3>SECURITY</h3>
                <p>Secure payment - our systems are protected with bank-grade security. Your payment is safe with us.</p>
            </div>
            <div>
                <h3>QUALITY</h3>
                <p>We work directly with over 40 specialist growers to bring you the best quality plants</p>
            </div>
            <div>
                <h3>PATCH PROMISE</h3>
                <p>If you need advice, just get in touch - we’ll be your personal plant gurus as long as you need us. If something’s up, tell us within 30 days of delivery — we’ll sort it.</p>
            </div>
        </div>
        <div class="social">
            <select>
                <option value="fr-paris"><span class="text">Paris - French</span></option>
                <option value="gb-london"><span class="text">UK - English</span></option>
            </select>        
            <ul class="social-footer">
                    <li>
                        <a href="#"><i class="bi bi-facebook"></i></a>
                        <a href="#"><i class="bi bi-twitter"></i></a>
                        <a href="#"><i class="bi bi-instagram"></i></a>
                    </li>
                </ul>

        </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="../js/jquery/jquery-2.2.4.min.js"></script>

<!-- <script src="../js/event.js"></script>-->
<script src="../js/utilities.js"></script>
<script src="../js/event.js"></script>
<script src="../js/shop.js"></script>
<script src="../js/panier.js"></script>
<script src="../js/checkout.js"></script>


    
</body>
</html>