<main class="margin-auto">
    <section class="section-header btn-success py-2 text-center ">
        <i class="bi  bi-chevron-compact-up text-success"></i>
        <ul class=slire>
            <li class=" slidregis show">Score 15% off pet-friendly and classic plant subscriptions. Terms apply.</li>
            <li class= "slidregis hide">Looking for a last minute gift? Shop our Digital Gift Cards!</li>
            <li class= "slidregis hide">Up to 50% off top-selling Plants, Planters, and Bundles!</li>

        </ul>
    </section>
    <sectin class="container col-12 mt-5">
        <article class="row">
            <div class="register offset-2 col-3  ">
                <span class="m-2 text-secondary">Register</span>
                <h2>Create Account</h2>
                <span class="mt-5">Do you already an account? <a href='login.php' class=' text-success'>login<i class="bi bi-arrow-right font-weight-bold"></i></a>
            </div>
            <div class="register offset-1 col-5">
            <?php if(isset($message)) :?>
            <p class="text-danger"><?= $message ?></p>
                    <?php endif ;?>
                <form class="form" action="register.php" method="post">
                    <div class="form-group d-block ">
                        <label >First Name</label>
                        <input type="text" class="form-control " name="firstName" id="firstName">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your name with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Last Name</label>
                        <input type="text" class="form-control" name="lastName" id="lastName">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your name with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" name="email" id="adressmail" aria-describedby="emailHelp">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" name="password" id="exampleInputPassword1">
                    </div>
                    <input type="submit" class="main-dark-button btn-success d-block m-auto col-2 py-3 input" value="create">
                </form>
                <p class="mt-3">By creating an account, I agree to receive reward program communications at the email address provided. If you don't see your welcome Gift in your inbox, check your Promotions folder. Add <a href="#">email</a> as a contact to ensure emails get delivered right to your inbox. View our Terms of Service and Privacy Policy for details.</p>
            </div>
        </article>
    </sectin>
    <script src='../js/regis.js'></script>
</main>