
<form action="addauthors.php" method="post" class="addcateg">
    <input type="hidden" name="id" class="form-control" id="exampleFormControlInput1" >
    <table class="table table border col-12 ">
        <thead class="col-6 offset-3">
            <tr class="col-6 offset-3">
                <th scope="col">Author</th>
                <th scope="col">ajouter</th>
            </tr>
        </thead>
        <tbody>
            <tr class="col-6 offset-3">
                <td ><input type="text" name="author" class="form-control col-4" id="exampleFormControlInput1" ></td>
                <td ><input type="submit" class="btn  border btn-danger col-2" value="enregistrer"></td>

            </tr>

        </tbody>
    </table>
</form>
