
<main class="tablepost">
        <table class="table border col-12">
            <thead>
                <tr>
                    <th scope="col">image</th>
                    <th scope="col">product</th>
                    <th scope="col">description</th>
                    <th scope="col">price</th>
                    <th scope="col">created-at</th>
                    <th scope="col">modiffier</th>
                    <th scope="col">supprimer</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($posts as $post):?>
                    <tr>
                        <td class="col-2 offset-1"><img src="../img/<?= $post['image']?>" class="w-100" /></td>
                        <td><?=$post['title']?></td>
                        <td><?=$post['content']?></td>
                        <td><?=$post['price']?></td>
                        <td><?=$post['created-at']?></td>
                        <td><a href="updatpost.php?idmodiff=<?=$post['id']?>" class="btn border btn-primary" >modifier</a></td>
                        <td><a href="deletepost.php?idsupp=<?=$post['id']?>" class="btn  border btn-danger ">supprimer</a></td>
                    </tr>
                <?php endforeach;?>

            </tbody>
        </table>

    </main>

