<main class="categorypost">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Categorie</th>
       <th scope="col">Nombre d'article</th>
        <th scope="col">modifier</th>
        <th scope="col">suuprimer</th>
    </thead>
    <tbody>
    <?php foreach($categories as $category) : ?>
      <tr>
        <td><?=  $category['id']?></td>
        <td><?=  $category['category']?></td>
        <td><?=  $category['count']?></td>
        <td><a class="btn btn-primary" href="updatcateg.php?idchang=<?= $category['id'] ?>">modifier</a></td>
        <td><a class="btn btn-danger" href="deletecatg.php?idsupprime=<?= $category['id'] ?>">supprimer</a></td>

      </tr>
      <?php endforeach ;?>
    
    </tbody>
  </table>
</main>